---
title: 
    <font class = "title-panel"> PPOL564 | Data Science I - Foundations  </font>
  <font size=100, face="bold"> Data Types in Python </font>
  <br>
  <br>
author: 
  <font class = "title-footer"> 
  &emsp;Prof. Eric Dunford &emsp;&#9670;&emsp; Georgetown University &emsp;&#9670;&emsp; McCourt School of Public Policy &emsp;&#9670;&emsp; eric.dunford@georgetown.edu</font>
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: "gu-theme.css"
    nature:
      beforeInit: "macros.js"
      highlightStyle: github
      countIncrementalSlides: True
      highlightLines: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,message=F,error=F,warning = F,
                      python.reticulate=T)
require(tidyverse)
require(here)
require(kableExtra)
Sys.setenv(RETICULATE_PYTHON = '/usr/local/bin/python3')
```

layout: true

<div class="slide-footer"><span> 
PPOL564 | Data Science I - Foundations

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

Class 4 <!-- Week of the Footer Here -->

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

Data Types in Python <!-- Title of the lecture here -->

</span></div> 



---
class: outline

# Outline for Today 

- **_Objects_**

- Cover the **_standard data types_** in Python 

- **_Mutable_** vs. _**Immutable_** data types

- **_Copies_**

- Modules

- **Manipulating _Mutable_ Data Structures** (see other notebook)
 
- See supplement notebook for a more detailed look at the functionality of **_strings and dates_**. 

---

class: newsection

# Objects

---

# Objects

- `=` assignment operator. 


- An objects "type" is defined at runtime; also known as "ducktyping"
  - differs from other languages where type must be made explicit; Python is a dynamically typed language.
  - type cannot be changed once established.
  - An objects class provides a blueprint for object behavior and function.
  
- reference is assigned to an object (e.g. below,  `x` references the object `4` in the statement `x = 4`)

- there can be multiple references to the same object (more on this below)

- objects are assigned a unique object id when initiated.

---

# Objects

![:space 5]

```{python,highlight=T}
x = 4
x
```

--

```{python}
type(x)
```

--

```{python}
id(x) # Identity of the object
```

---

# Objects

Instantiate objects upon assignment.

```{python,eval=F}
x = 4
```

--

The class defines how the object behaves to different opertions. We use the pointer `.` to access an objects methods. 

```{python,eval=F,highlight}
x.
  |
  V
   __add__()  # method dictating behavior to the `+` operator 
   __mult__() # method dictating behavior to the `*` operator 
   __mod__()  # method dictating behavior to the `%` operator 
   __eq__()   # method dictating behavior to the `==` operator 
     .
     .
     .
```


---

# Objects

Instantiate objects upon assignment.

```{python,eval=F}
x = [1,2,3,4]
```

Data classes provide a blueprint for object behavior and functionality (methods). 

```{python,eval=F,highlight=T}
x.
  |
  V
   append()  # method for appending entries 
   clear()   # method clearing all values from object instance 
   copy()    # method for creating a shallow copy 
   sort()    # method sorting values 
   pop()     # method for removing values for use
   reverse() # method sorting values in reverse
     .
     .
     .
```

---

class: newsection

# Data Types

---

# Data Types

![:space 10]

**_Two ways of instanitating a data class in Python_**

![:space 5]

1. **Literals**: syntatic representation in Python, e.g. `[]`

2. **Constructors**: class constructor, e.g. `list()`

---

# Scalar Data Types

![:space 15]
.center[
|  type | Description | Example
|:-----:|:-------------:|:-----------:|
| `int`| integer types | `4` |
|`float`| 64-bit floating point numbers | `4.567` |
|`bool`| boonlean logical values | `True`|
| `None`|  null object (serves as a valuable place holder) | `None` |
]

---

## `int` type

`int` literal
```{python}
x = 1
type(x)
```

`int` constructor
```{python}
int(3.4)
```

```{python,tidy=T}
dir(x)
```

---

## `float` type

`float` literal
```{python}
x = 1.0
type(x)
```

`float` constructor
```{python}
float(3)
```

```{python,tidy=T}
dir(x)
```

---

## `bool` type

`float` literal
```{python}
x = True
type(x)
```

`bool` constructor
```{python}
bool(0)
```

```{python,tidy=T}
dir(x)
```

---

## `None` type

`None` literal
```{python}
x = None
type(x)
```


```{python,tidy=T}
dir(x)
```

```{python}
x is None
```

---

# Collection Data Types

![:space 10]

.center[
|  Type   |  Description  | Example | Mutable | 
|:------:|:------:|:------:|:------:|
| `list` | heterogeneous sequences of objects | `[1,2,3]` | &#10003; |
| `str`  | sequences of characters | `"A word"` | &#10008; |
| `dicts`|  associative array of key/value mappings | `{"a": 1}`| keys &#10008; values  &#10003;
| `sets` | unordered collection of _distinct_ objects | `{1,2,3}` | &#10003; |
|`tuples`| heterogeneous sequence | `(1,2)` | &#10008; | 
]

![:space 2]

We can access the information contained within python collection types using a 0-based index if the container contains an `.index()` method

---

## `list` type

Allows for heterogeneous membership in the various object types

<br>
`list` literal
```{python}
x = [1, 2.2, "str", True, None] 
type(x)
```


`list` constructor

```{python}
x = list("This")
type(x)
```

---

## `str` type


<br>
`str` literal
```{python}
x = "This is a sentence"
type(x)
```


`str` constructor

```{python}
x = str(12345)
type(x)
```


---

## `dict` type

Associative array of key-value pairs; indexed ("hashed") by the keys

`dict` literal
```{python}
x = {'a':1,'b':2,'c':-2}
type(x)
```


`dict` constructor

```{python}
x = dict(a = 1,b = 2, c= -2)
type(x)
```

---

## `set` type

Unordered collection of unique elements

`set` literal
```{python}
x = {1,2,-2}
type(x)
```


`set` constructor

```{python}
x = set([1,2,-2])
type(x)
```


---

## `tuple` type

Heterogeneous but immutable collection of other data types.

`tuple` literal
```{python}
x = (1,2)
type(x)
```


`set` constructor

```{python}
x = tuple([1,2,-2])
type(x)
```

