---
title: 'PPOL564 | Reading List'
date: 'Fall 2019'
output: 
  html_document:
    css: style.css
    theme: cerulean
    highlight: default
    toc_depth: 3
    toc: true
    toc_collapsed: true
    toc_float: true
---

### [Home](../index.html)

### Class 1: Reproducibility

- _Required Readings_
  - [The Plain Person's Guide to Plain Text Social Science](http://plain-text.co/) - Kieran Healy
    + Ch. 1: Introduction
    + Ch. 2: Keep a Record
    + Ch. 3: Write and Edit
    + Ch. 4: Reproduce Work
    
    
### Class 2: Version Control

- _Required Readings_
  - [Pro Git](https://git-scm.com/book/en/v2) - Chacon & Straub 
    + Ch. 1: Getting Started
    + Ch. 2: Git Basics
    
### Class 3: Python Notebooks

- _Required Readings_
  + [Jupyter Notebook for Beginners: A tutorial](https://www.dataquest.io/blog/jupyter-notebook-tutorial/) - Pryke, Benjamin. www.dataquest.io
  + [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) by Jake VanderPlas
    + [Help and Documentation in IPython](https://jakevdp.github.io/PythonDataScienceHandbook/01.01-help-and-documentation.html)
    + [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html)
    + [Input and Output History](https://jakevdp.github.io/PythonDataScienceHandbook/01.04-input-output-history.html)
    + [IPython and Shell Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.05-ipython-and-shell-commands.html)
    
- <font color = "grey">**_Additional Resources and Suggested Materials_**</font> 
  + [More IPython Resources](https://jakevdp.github.io/PythonDataScienceHandbook/01.08-more-ipython-resources.html)
  
### Class 4: Data Types in Python

- _Required Readings_
    - Lutz - Ch. 4 (See Canvas)
    
- <font color = "grey">**_Additional Resources and Suggested Materials_**</font> 
    - [Mutable vs Immutable Objects in Python](https://medium.com/@meghamohan/mutable-and-immutable-side-of-python-c2145cf72747)
    - [Installing Packages using PyPi](https://packaging.python.org/tutorials/installing-packages/) (i.e. installing packages using the `pip` shell command)
    - [Installing Packages using Anaconda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html) (i.e. installing packages using the `conda` shell command. Requires having an Anaconda distribution installed.)
    
### Class 5: Control Sequences, Iteration, and Functions

- _Required Readings_
    - [Repeated Actions with Loops](https://swcarpentry.github.io/python-novice-inflammation/02-loop/index.html) - Data Carpentry
    - [Making Choices](https://swcarpentry.github.io/python-novice-inflammation/05-cond/index.html) - Data Carpentry
    - [Creating Functions ](https://swcarpentry.github.io/python-novice-inflammation/06-func/index.html) - Data Carpentry
    
### Class 6: Comprehensions and Generators

- _Required Readings_
    - Lutz - Ch.14 (See Canvas)
    
### Class 7: Numpy
  
- _Required Readings_
  - [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) by Jake VanderPlas
      + All of Chapter 2
        + [Understanding Data Types in Python](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)
        + [The Basics of NumPy Arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)
        + [Computation on NumPy Arrays: Universal Functions](https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html)
        + [Aggregations: Min, Max, and Everything In Between](https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html)
        + [Computation on Arrays: Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)
        + [Comparisons, Masks, and Boolean Logic](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html)
        + [Fancy Indexing](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html)
        + [Sorting Arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html)
        + [Structured Data: NumPy's Structured Arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.09-structured-data-numpy.html)


### Class 8: Data Wrangling with Pandas (part 1)

- _Required Readings_
  - [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) by Jake VanderPlas
     + [Introducing Pandas Objects](https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html)
     + [Data Indexing and Selection](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html)
     + [Handling Missing Data](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html)
     + [Hierarchical Indexing](https://jakevdp.github.io/PythonDataScienceHandbook/03.05-hierarchical-indexing.html)
     + [Combining Datasets: Concat and Append](https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html)
     + [Combining Datasets: Merge and Join](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html)

### Class 9: Data Wrangling with Pandas (part 2)

- _Required Readings_
  - [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) by Jake VanderPlas
    + [Aggregation and Grouping](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html)
    + [Pivot Tables](https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html)
    + [High-Performance Pandas: `eval()` and `query()`](https://jakevdp.github.io/PythonDataScienceHandbook/03.12-performance-eval-and-query.html)

### Class 10: Exploratory Data Analysis

- _Required Readings_
  - [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) by Jake VanderPlas
     + [Simple Line Plots](https://jakevdp.github.io/PythonDataScienceHandbook/04.01-simple-line-plots.html)
     + [Simple Scatter Plots](https://jakevdp.github.io/PythonDataScienceHandbook/04.02-simple-scatter-plots.html)
     + [Density and Contour Plots](https://jakevdp.github.io/PythonDataScienceHandbook/04.04-density-and-contour-plots.html)
     + [Histograms, Binnings, and Density](https://jakevdp.github.io/PythonDataScienceHandbook/04.05-histograms-and-binnings.html)
     + [Multiple Subplots](https://jakevdp.github.io/PythonDataScienceHandbook/04.08-multiple-subplots.html)
     + [Visualization with Seaborn](https://jakevdp.github.io/PythonDataScienceHandbook/04.14-visualization-with-seaborn.html)

### Class 11 + 12: Vectors + Trigonometry of Vectors 

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 1, 2, 12.1, 12.3

### Class 13 + 14: Matrix Transformations + Matrix Operations and Inversions 

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 12.3 - 12.6, 13

### Class 15: Linear Regression 

- _Required Readings_
  - [The Linear Algebra View of Least-Squares Regression](https://medium.com/@andrew.chamberlain/the-linear-algebra-view-of-least-squares-regression-f67044b7f39b) - Andrew Chamberlain

### Class 16 + 17: Eigen Decompositions

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 14.1

### Class 18: Differentiation

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 3 - 6

### Class 19: Optimizing Univariate Functions

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 8, 15.1-15.2.2

### Class 20: Optimizing Multivariate Functions

- _Required Readings_
  - **Moore and Siegel**
      + Ch.15.3-16.1

### Class 21: Gradient Descent

- _Required Readings_
  - [Introduction to the Gradient Descent Algorithm](https://medium.com/@montjoile/an-introduction-to-gradient-descent-algorithm-34cf3cee752b) - Sara Garcia
  - [Gradient Descent - Simply Explained](https://towardsdatascience.com/gradient-descent-simply-explained-1d2baa65c757) - Koo Shung

### Class 22: Constrained Optimization 

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 16

### Class 23: Probability

- _Required Readings_
  - **Moore and Siegel**
      + Ch. 9.1 - 9.2.2
      + Ch. 10.1 - 10.6.2, 10.7
      + 11.1 - 11.2.2, 11.3.1 - 11.3.4

### Class 24: Bayes Rule + Naive Bayes Algorithm

- _Required Readings_
  - **Moore and Siegel**
      - Ch. 9.2.3
  - [A Gentle Introduction to Bayes Theorem for Machine Learning](https://machinelearningmastery.com/bayes-theorem-for-machine-learning/) - Brownlee, Jason
  - [Naive Bayes from Scratch](https://machinelearningmastery.com/classification-as-conditional-probability-and-the-naive-bayes-algorithm/) - Brownlee, Jason



### Class 25: Simulation and Sampling    

- _Required Readings_
  - McElreath, Richard. Statistical rethinking: A Bayesian course with examples in R and Stan. Chapman and Hall/CRC, 2018.
      - Ch. 3 (Canvas)
      - Ch. 8.1 - 8.3 (Canvas)
 

    




